--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

-- Started on 2025-04-11 20:21:15 MSK

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16460)
-- Name: films; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.films (
    id bigint NOT NULL,
    name character varying NOT NULL,
    description character varying,
    release_date date,
    duration integer,
    genre character varying,
    rating numeric(3,1)
);


ALTER TABLE public.films OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16459)
-- Name: films_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.films ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.films_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16474)
-- Name: review; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.review (
    id bigint NOT NULL,
    text character varying,
    rating numeric(3,1),
    film_id bigint,
    user_id bigint
);


ALTER TABLE public.review OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16473)
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16452)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying,
    login character varying,
    name character varying,
    birthday date
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16451)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3616 (class 0 OID 16460)
-- Dependencies: 220
-- Data for Name: films; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.films (id, name, description, release_date, duration, genre, rating) FROM stdin;
9	Comedy	descr	1995-07-15	110	COMEDY	7.2
3	Fil3	third film	2000-07-15	105	ACTION	6.5
2	Film2	second film	2000-07-15	98	ACTION	8.6
10	Drama	descr	1995-07-15	107	DRAMA	9.0
12	Form	form	2000-09-18	100	ROMANCE	\N
1	Film	first film	2000-07-15	127	ACTION	7.4
\.


--
-- TOC entry 3618 (class 0 OID 16474)
-- Dependencies: 222
-- Data for Name: review; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.review (id, text, rating, film_id, user_id) FROM stdin;
2	normal	8.5	10	2
1	review	7.0	1	2
\.


--
-- TOC entry 3614 (class 0 OID 16452)
-- Dependencies: 218
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, login, name, birthday) FROM stdin;
2	mary@mail.ru	little_devil	Mary	2000-06-03
3	kate@mail.ru	kate	Kate	2001-08-17
5	Chyna.Beatty70@yahoo.com	BS5CqsUHCY	Katrina Bailey	1983-12-07
\.


--
-- TOC entry 3624 (class 0 OID 0)
-- Dependencies: 219
-- Name: films_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.films_id_seq', 13, true);


--
-- TOC entry 3625 (class 0 OID 0)
-- Dependencies: 221
-- Name: review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.review_id_seq', 10, true);


--
-- TOC entry 3626 (class 0 OID 0)
-- Dependencies: 217
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 5, true);


--
-- TOC entry 3463 (class 2606 OID 16466)
-- Name: films films_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.films
    ADD CONSTRAINT films_pk PRIMARY KEY (id);


--
-- TOC entry 3465 (class 2606 OID 16480)
-- Name: review review_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pk PRIMARY KEY (id);


--
-- TOC entry 3461 (class 2606 OID 16458)
-- Name: users users_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pk PRIMARY KEY (id);


--
-- TOC entry 3466 (class 2606 OID 16481)
-- Name: review fk_film; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk_film FOREIGN KEY (film_id) REFERENCES public.films(id);


--
-- TOC entry 3467 (class 2606 OID 16486)
-- Name: review fk_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public.users(id);


-- Completed on 2025-04-11 20:21:15 MSK

--
-- PostgreSQL database dump complete
--

